In [117]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [44]:
X_train_NN = np.loadtxt('X_train_NN.txt')
Y_train = np.loadtxt('Y_train.txt')
X_test_NN = np.loadtxt('X_test_NN.txt')
Y_test  = np.loadtxt('Y_test.txt')

In [45]:
y_lab = []
for i in range(59):
    if Y_test[i][0] == 1.0:
        y_lab.append(1)
    if Y_test[i][1] == 1.0:
        y_lab.append(2)
    if Y_test[i][2] == 1.0:
        y_lab.append(3)
    if Y_test[i][3] == 1.0:
        y_lab.append(4)
    

In [46]:
model_NN  = tf.keras.models.Sequential()

model_NN.add(tf.keras.layers.Dense(units= 128, activation= 'relu', input_shape = (650,)))
model_NN.add(tf.keras.layers.Dense(units = 32, activation = 'relu'))
model_NN.add(tf.keras.layers.Dense(units= 4, activation= 'softmax'))
model_NN.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 128)               83328     
_________________________________________________________________
dense_11 (Dense)             (None, 32)                4128      
_________________________________________________________________
dense_12 (Dense)             (None, 4)                 132       
Total params: 87,588
Trainable params: 87,588
Non-trainable params: 0
_________________________________________________________________


In [47]:
model_NN.compile(optimizer="adam", loss='categorical_crossentropy', metrics=['accuracy'])

In [48]:
model_NN.fit(X_train_NN, Y_train, epochs= 5)

Epoch 1/5
210/210 [==============================] - 0s 746us/sample - loss: 35.2118 - acc: 0.2667
Epoch 2/5
210/210 [==============================] - 0s 110us/sample - loss: 13.4905 - acc: 0.3571
Epoch 3/5
210/210 [==============================] - 0s 118us/sample - loss: 9.5107 - acc: 0.4333
Epoch 4/5
210/210 [==============================] - 0s 106us/sample - loss: 5.7752 - acc: 0.5143
Epoch 5/5
210/210 [==============================] - 0s 113us/sample - loss: 3.0905 - acc: 0.6619


In [49]:
model_NN.evaluate(X_test_NN, Y_test)

59/59 [==============================] - 0s 1ms/sample - loss: 8.4566 - acc: 0.3220


[8.456582974579375, 0.3220339]

In [50]:
y_predNN = model_NN.predict_classes(X_test_NN, verbose= 1)
print(metrics.confusion_matrix(y_predNN, y_lab))

59/59 [==============================] - 0s 932us/sample
[[0 5 2 5 5]
 [0 0 6 4 0]
 [0 6 4 3 7]
 [0 2 4 1 5]
 [0 0 0 0 0]]


In [51]:
X_train = X_train_NN.reshape(210, 13,50)
X_test = X_test_NN.reshape(X_test_NN.shape[0], 13,50)

In [52]:
model_CNN  = tf.keras.models.Sequential()

model_CNN.add( tf.keras.layers.Conv1D(filters= 32, kernel_size= 3, padding = 'same', activation= 'relu', input_shape =[13,50]))
model_CNN.add( tf.keras.layers.MaxPool1D(pool_size= 2, strides = 1, padding = 'same'))
model_CNN.add( tf.keras.layers.Conv1D(filters= 64, kernel_size= 3, padding = 'same', activation= 'relu'))
model_CNN.add( tf.keras.layers.MaxPool1D(pool_size= 2, strides = 1, padding = 'same'))
model_CNN.add(tf.keras.layers.Dropout(0.25))

model_CNN.add(tf.keras.layers.Flatten())

model_CNN.add(tf.keras.layers.Dense(units = 128, activation= 'relu'))
model_CNN.add(tf.keras.layers.Dropout(0.25))

model_CNN.add(tf.keras.layers.Dense(units = 4, activation= 'softmax'))

model_CNN.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_3 (Conv1D)            (None, 13, 32)            4832      
_________________________________________________________________
max_pooling1d_3 (MaxPooling1 (None, 13, 32)            0         
_________________________________________________________________
conv1d_4 (Conv1D)            (None, 13, 64)            6208      
_________________________________________________________________
max_pooling1d_4 (MaxPooling1 (None, 13, 64)            0         
_________________________________________________________________
dropout_4 (Dropout)          (None, 13, 64)            0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 832)               0         
_________________________________________________________________
dense_13 (Dense)             (None, 128)              

In [53]:
model_CNN.compile(optimizer="adam", loss='categorical_crossentropy', metrics=['accuracy'])

In [54]:
model_CNN.fit(X_train, Y_train, epochs = 5)

Epoch 1/5
210/210 [==============================] - 0s 1ms/sample - loss: 52.1234 - acc: 0.2952
Epoch 2/5
210/210 [==============================] - 0s 208us/sample - loss: 26.8625 - acc: 0.2571
Epoch 3/5
210/210 [==============================] - 0s 214us/sample - loss: 12.4593 - acc: 0.2667
Epoch 4/5
210/210 [==============================] - 0s 207us/sample - loss: 6.3513 - acc: 0.3143
Epoch 5/5
210/210 [==============================] - 0s 211us/sample - loss: 4.7052 - acc: 0.3905


In [55]:
model_CNN.evaluate(X_test, Y_test)

59/59 [==============================] - 0s 2ms/sample - loss: 3.0117 - acc: 0.2712


[3.0116913641913463, 0.27118644]

In [56]:
y_predCNN = model_CNN.predict_classes(X_test, verbose= 1)
print(metrics.confusion_matrix(y_predCNN, y_lab))

59/59 [==============================] - 0s 1ms/sample
[[ 0  2  1  1  0]
 [ 0  9 13 12 16]
 [ 0  1  0  0  0]
 [ 0  1  2  0  1]
 [ 0  0  0  0  0]]


In [57]:
model_RNN = tf.keras.models.Sequential()
model_RNN.add(tf.keras.layers.LSTM(150, input_shape= (13,50)))
model_RNN.add(tf.keras.layers.Dropout(0.2))
model_RNN.add(tf.keras.layers.Dense(units = 4, activation= 'softmax'))
model_RNN.summary()



Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 150)               120600    
_________________________________________________________________
dropout_6 (Dropout)          (None, 150)               0         
_________________________________________________________________
dense_15 (Dense)             (None, 4)                 604       
Total params: 121,204
Trainable params: 121,204
Non-trainable params: 0
_________________________________________________________________


In [58]:
model_RNN.compile(optimizer="adam", loss='categorical_crossentropy', metrics=['accuracy'] )

In [59]:
model_RNN.fit(X_train, Y_train, epochs = 5)

Epoch 1/5
210/210 [==============================] - 1s 3ms/sample - loss: 1.5856 - acc: 0.2095
Epoch 2/5
210/210 [==============================] - 0s 884us/sample - loss: 1.1577 - acc: 0.5238
Epoch 3/5
210/210 [==============================] - 0s 952us/sample - loss: 0.8966 - acc: 0.7524
Epoch 4/5
210/210 [==============================] - 0s 870us/sample - loss: 0.7382 - acc: 0.8571
Epoch 5/5
210/210 [==============================] - 0s 929us/sample - loss: 0.5941 - acc: 0.9286


In [60]:
model_RNN.evaluate(X_test,Y_test)

59/59 [==============================] - 0s 3ms/sample - loss: 1.3115 - acc: 0.3220


[1.3115336106995406, 0.3220339]

In [61]:
y_predRNN = model_RNN.predict_classes(X_test, verbose= 1)
print(metrics.confusion_matrix(y_predRNN, y_lab))

59/59 [==============================] - 0s 2ms/sample
[[0 3 2 1 3]
 [0 3 6 6 3]
 [0 4 1 3 4]
 [0 3 7 3 7]
 [0 0 0 0 0]]


In [62]:
## Normalizing the dataset

In [63]:
X_train_NN_Norm = preprocessing.normalize(X_train_NN)
X_test_NN_Norm = preprocessing.normalize(X_test_NN)

In [64]:
model_NN_Norm_MFCC  = tf.keras.models.Sequential()

model_NN_Norm_MFCC.add(tf.keras.layers.Dense(units= 128, activation= 'relu', input_shape = (650,)))
model_NN_Norm_MFCC.add(tf.keras.layers.Dense(units = 32, activation = 'relu'))
model_NN_Norm_MFCC.add(tf.keras.layers.Dense(units= 4, activation= 'softmax'))
model_NN_Norm_MFCC.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 128)               83328     
_________________________________________________________________
dense_17 (Dense)             (None, 32)                4128      
_________________________________________________________________
dense_18 (Dense)             (None, 4)                 132       
Total params: 87,588
Trainable params: 87,588
Non-trainable params: 0
_________________________________________________________________


In [65]:
model_NN_Norm_MFCC.compile(optimizer="adam", loss='categorical_crossentropy', metrics=['accuracy'])

In [66]:
model_NN_Norm_MFCC.fit(X_train_NN_Norm, Y_train, epochs= 5)

Epoch 1/5
210/210 [==============================] - 0s 775us/sample - loss: 1.3737 - acc: 0.2952
Epoch 2/5
210/210 [==============================] - 0s 111us/sample - loss: 1.3434 - acc: 0.3429
Epoch 3/5
210/210 [==============================] - 0s 116us/sample - loss: 1.3314 - acc: 0.3429
Epoch 4/5
210/210 [==============================] - 0s 112us/sample - loss: 1.3237 - acc: 0.3429
Epoch 5/5
210/210 [==============================] - 0s 115us/sample - loss: 1.3142 - acc: 0.3429


In [67]:
model_NN_Norm_MFCC.evaluate(X_test_NN_Norm, Y_test)

59/59 [==============================] - 0s 2ms/sample - loss: 1.3824 - acc: 0.2712


[1.3824218309531777, 0.27118644]

In [69]:
X_train_Norm = np.empty([210,13,50])
for i in range(X_train.shape[0]):
    X_train_Norm[i] = preprocessing.normalize(X_train[i])


In [70]:
X_test_Norm = np.empty([59,13,50])
for i in range(X_test.shape[0]):
    X_test_Norm[i] = preprocessing.normalize(X_test[i])

In [76]:
model_CNN_Norm  = tf.keras.models.Sequential()

model_CNN_Norm.add( tf.keras.layers.Conv1D(filters= 8, kernel_size= 3, padding = 'same', activation= 'relu', input_shape =[13,50]))
model_CNN_Norm.add( tf.keras.layers.MaxPool1D(pool_size= 2, strides = 1, padding = 'same'))
model_CNN_Norm.add(tf.keras.layers.Dropout(0.25))

model_CNN_Norm.add(tf.keras.layers.Flatten())

model_CNN_Norm.add(tf.keras.layers.Dense(units = 4, activation= 'softmax'))

model_CNN_Norm.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_6 (Conv1D)            (None, 13, 8)             1208      
_________________________________________________________________
max_pooling1d_6 (MaxPooling1 (None, 13, 8)             0         
_________________________________________________________________
dropout_8 (Dropout)          (None, 13, 8)             0         
_________________________________________________________________
flatten_4 (Flatten)          (None, 104)               0         
_________________________________________________________________
dense_20 (Dense)             (None, 4)                 420       
Total params: 1,628
Trainable params: 1,628
Non-trainable params: 0
_________________________________________________________________


In [77]:
model_CNN_Norm.compile(optimizer="adam", loss='categorical_crossentropy', metrics=['accuracy'])

In [78]:
model_CNN_Norm.fit(X_train_Norm, Y_train, epochs= 5)

Epoch 1/5
210/210 [==============================] - 0s 928us/sample - loss: 1.4021 - acc: 0.2524
Epoch 2/5
210/210 [==============================] - 0s 137us/sample - loss: 1.3802 - acc: 0.3143
Epoch 3/5
210/210 [==============================] - 0s 121us/sample - loss: 1.3554 - acc: 0.3000
Epoch 4/5
210/210 [==============================] - 0s 132us/sample - loss: 1.3522 - acc: 0.3238
Epoch 5/5
210/210 [==============================] - 0s 132us/sample - loss: 1.3307 - acc: 0.3667


In [79]:
model_CNN_Norm.evaluate(X_test_Norm, Y_test)

59/59 [==============================] - 0s 2ms/sample - loss: 1.3947 - acc: 0.3390


[1.3947178428455935, 0.33898306]

In [80]:
model_RNN_Norm = tf.keras.models.Sequential()
model_RNN_Norm.add(tf.keras.layers.LSTM(150, input_shape= (13,50)))
model_RNN_Norm.add(tf.keras.layers.Dropout(0.2))
model_RNN_Norm.add(tf.keras.layers.Dense(units = 4, activation= 'softmax'))
model_RNN_Norm.summary()



Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 150)               120600    
_________________________________________________________________
dropout_9 (Dropout)          (None, 150)               0         
_________________________________________________________________
dense_21 (Dense)             (None, 4)                 604       
Total params: 121,204
Trainable params: 121,204
Non-trainable params: 0
_________________________________________________________________


In [81]:
model_RNN_Norm.compile(optimizer="adam", loss='categorical_crossentropy', metrics=['accuracy'])

In [82]:
model_RNN_Norm.fit(X_train_Norm, Y_train, epochs= 5)

Epoch 1/5
210/210 [==============================] - 1s 4ms/sample - loss: 1.3774 - acc: 0.2476
Epoch 2/5
210/210 [==============================] - 0s 936us/sample - loss: 1.3357 - acc: 0.3762
Epoch 3/5
210/210 [==============================] - 0s 997us/sample - loss: 1.3159 - acc: 0.3714
Epoch 4/5
210/210 [==============================] - 0s 1ms/sample - loss: 1.2965 - acc: 0.3714
Epoch 5/5
210/210 [==============================] - 0s 1ms/sample - loss: 1.2750 - acc: 0.4143


In [83]:
model_RNN_Norm.evaluate(X_test_Norm, Y_test)

59/59 [==============================] - 0s 3ms/sample - loss: 1.3862 - acc: 0.3220


[1.386245426485094, 0.3220339]

In [ ]:
## Conversion by taking mean 

In [87]:
X_mean_train = np.empty([210,13]) 
lc = X_train.shape[0]
for i in range(lc):
    for j in range(13):
        X_mean_train[i][j] = sum(X_train[i][j])/len(X_train[i][j])
    

In [88]:
X_mean_test = np.empty([59,13]) 
lc = X_test.shape[0]
for i in range(lc):
    for j in range(13):
        X_mean_test[i][j] = sum(X_test[i][j])/len(X_test[i][j])
    

In [97]:
y_ne_train = []
for i in range(210):
    if Y_train[i][0] == 1.0:
        y_ne_train.append(1)
    if Y_train[i][1] == 1.0:
        y_ne_train.append(2)
    if Y_train[i][2] == 1.0:
        y_ne_train.append(3)
    if Y_train[i][3] == 1.0:
        y_ne_train.append(4)

In [98]:
y_notenc_train = np.array(y_ne_train)

In [99]:
y_ne_test = []
for i in range(59):
    if Y_test[i][0] == 1.0:
        y_ne_test.append(1)
    if Y_test[i][1] == 1.0:
        y_ne_test.append(2)
    if Y_test[i][2] == 1.0:
        y_ne_test.append(3)
    if Y_test[i][3] == 1.0:
        y_ne_test.append(4)
    

In [100]:
y_notenc_test = np.array(y_ne_test)

In [93]:
y_notenc_test

array([1, 2, 4, 4, 4, 1, 2, 4, 3, 2, 1, 2, 1, 1, 4, 4, 2, 4, 1, 3, 1, 3,
       4, 3, 1, 3, 3, 4, 3, 4, 2, 1, 4, 4, 3, 3, 1, 3, 3, 2, 4, 2, 1, 1,
       4, 4, 2, 2, 2, 2, 2, 3, 2, 1, 4, 3, 4, 2, 2])

In [167]:
rf = RandomForestClassifier(n_estimators= 1000, random_state= 42)
rf.fit(X_mean_train, y_notenc_train)
rf_pred = rf.predict(X_mean_test)
print(accuracy_score(y_notenc_test, rf_pred))

0.3389830508474576


In [168]:
svc_mfcc = SVC()
svc_mfcc.fit(X_mean_train, y_notenc_train)
svc_mfcc_pred = svc_mfcc.predict(X_mean_test)
print(accuracy_score(y_notenc_test, svc_mfcc_pred))

0.2711864406779661


/Users/rohithjanardhan/mlpath/yourenv/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [129]:
X_mean_norm_train = np.empty([210,13]) 
lc = X_train_Norm.shape[0]
for i in range(lc):
    for j in range(13):
        X_mean_norm_train[i][j] = sum(X_train_Norm[i][j])/len(X_train_Norm[i][j])

In [130]:
X_mean_norm_test = np.empty([59,13]) 
lc = X_test_Norm.shape[0]
for i in range(lc):
    for j in range(13):
        X_mean_norm_test[i][j] = sum(X_test_Norm[i][j])/len(X_test_Norm[i][j])

In [132]:
rf_norm_mfcc = RandomForestClassifier(n_estimators=1000, random_state=42)
rf_norm_mfcc.fit(X_mean_norm_train, y_notenc_train)
rf_pred_norm = rf_norm_mfcc.predict(X_mean_norm_test)
print(accuracy_score(y_notenc_test, rf_pred_norm))

0.23728813559322035


In [133]:
sv_norm_mfcc = SVC()
sv_norm_mfcc.fit(X_mean_norm_train, y_notenc_train)
sv_norm_mfcc_pred = sv_norm_mfcc.predict(X_mean_norm_test)
print(accuracy_score(y_notenc_test, sv_norm_mfcc_pred))

0.2711864406779661


/Users/rohithjanardhan/mlpath/yourenv/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [138]:
X_train_ms_NN = np.loadtxt('X_train_ms_NN.txt')
X_test_ms_NN = np.loadtxt('X_test_ms_NN.txt')

In [147]:
model_ms_NN  = tf.keras.models.Sequential()

model_ms_NN.add(tf.keras.layers.Dense(units= 128, activation= 'relu', input_shape = (6400,)))
model_ms_NN.add(tf.keras.layers.Dense(units = 32, activation = 'relu'))
model_ms_NN.add(tf.keras.layers.Dense(units= 4, activation= 'softmax'))
model_ms_NN.summary()
model_ms_NN.compile(optimizer="adam", loss='categorical_crossentropy', metrics=['accuracy'])

model_ms_NN.fit(X_train_ms_NN, Y_train, epochs = 5)
_,acc = model_ms_NN.evaluate(X_test_ms_NN, Y_test)
print('\n NN Accuracy is ',acc)

Model: "sequential_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_43 (Dense)             (None, 128)               819328    
_________________________________________________________________
dense_44 (Dense)             (None, 32)                4128      
_________________________________________________________________
dense_45 (Dense)             (None, 4)                 132       
Total params: 823,588
Trainable params: 823,588
Non-trainable params: 0
_________________________________________________________________
Epoch 1/5
210/210 [==============================] - 0s 2ms/sample - loss: 4.7130 - acc: 0.2667
Epoch 2/5
210/210 [==============================] - 0s 283us/sample - loss: 1.2885 - acc: 0.5048
Epoch 3/5
210/210 [==============================] - 0s 309us/sample - loss: 0.8964 - acc: 0.6190
Epoch 4/5
210/210 [==============================] - 0s 576us/sample - loss: 0.6693 -

In [148]:
X_train_ms = X_train_ms_NN.reshape(210,128,50)
X_test_ms = X_test_ms_NN.reshape(59,128,50)

In [149]:
model_ms_CNN  = tf.keras.models.Sequential()

model_ms_CNN.add( tf.keras.layers.Conv1D(filters= 8, kernel_size= 3, padding = 'same', activation= 'relu', input_shape =[128,50]))
model_ms_CNN.add( tf.keras.layers.MaxPool1D(pool_size= 2, strides = 1, padding = 'same'))
model_ms_CNN.add(tf.keras.layers.Dropout(0.25))

model_ms_CNN.add(tf.keras.layers.Flatten())

model_ms_CNN.add(tf.keras.layers.Dense(units = 4, activation= 'softmax'))

model_ms_CNN.summary()

model_ms_CNN.compile(optimizer="adam", loss='categorical_crossentropy', metrics=['accuracy'])

model_ms_CNN.fit(X_train_ms, Y_train, epochs = 5)
_,acc = model_ms_CNN.evaluate(X_test_ms, Y_test)
print('\n CNN Accuracy is ',acc)

Model: "sequential_20"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_7 (Conv1D)            (None, 128, 8)            1208      
_________________________________________________________________
max_pooling1d_7 (MaxPooling1 (None, 128, 8)            0         
_________________________________________________________________
dropout_10 (Dropout)         (None, 128, 8)            0         
_________________________________________________________________
flatten_5 (Flatten)          (None, 1024)              0         
_________________________________________________________________
dense_46 (Dense)             (None, 4)                 4100      
Total params: 5,308
Trainable params: 5,308
Non-trainable params: 0
_________________________________________________________________
Epoch 1/5
210/210 [==============================] - 0s 1ms/sample - loss: 6.1792 - acc: 0.2333
Epoch 2/5
210/210 [==

In [150]:
model_ms_RNN = tf.keras.models.Sequential()
model_ms_RNN.add(tf.keras.layers.LSTM(150, input_shape= (128,50)))
model_ms_RNN.add(tf.keras.layers.Dropout(0.2))
model_ms_RNN.add(tf.keras.layers.Dense(units = 4, activation= 'softmax'))
model_ms_RNN.summary()

model_ms_RNN.compile(optimizer="adam", loss='categorical_crossentropy', metrics=['accuracy'])
model_ms_RNN.fit(X_train_ms, Y_train, epochs= 5)
_,acc = model_ms_RNN.evaluate(X_test_ms, Y_test)
print('\n RNN Accuracy is ',acc)


Model: "sequential_21"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 150)               120600    
_________________________________________________________________
dropout_11 (Dropout)         (None, 150)               0         
_________________________________________________________________
dense_47 (Dense)             (None, 4)                 604       
Total params: 121,204
Trainable params: 121,204
Non-trainable params: 0
_________________________________________________________________
Epoch 1/5
210/210 [==============================] - 2s 10ms/sample - loss: 1.3881 - acc: 0.3286
Epoch 2/5
210/210 [==============================] - 2s 7ms/sample - loss: 1.3616 - acc: 0.3762
Epoch 3/5
210/210 [==============================] - 2s 7ms/sample - loss: 1.3370 - acc: 0.3857
Epoch 4/5
210/210 [==============================] - 2s 7ms/sample - loss: 1.3022 - acc:

In [151]:
X_train_ms_Norm_NN  = preprocessing.normalize(X_train_ms_NN)
X_test_ms_Norm_NN = preprocessing.normalize(X_test_ms_NN)

In [153]:
model_ms_NN_Norm  = tf.keras.models.Sequential()

model_ms_NN_Norm.add(tf.keras.layers.Dense(units= 128, activation= 'relu', input_shape = (6400,)))
model_ms_NN_Norm.add(tf.keras.layers.Dense(units = 32, activation = 'relu'))
model_ms_NN_Norm.add(tf.keras.layers.Dense(units= 4, activation= 'softmax'))
model_ms_NN_Norm.summary()
model_ms_NN_Norm.compile(optimizer="adam", loss='categorical_crossentropy', metrics=['accuracy'])

model_ms_NN_Norm.fit(X_train_ms_Norm_NN, Y_train, epochs = 5)
_,acc = model_ms_NN_Norm.evaluate(X_test_ms_Norm_NN, Y_test)
print('\n NN Accuracy is ',acc)

Model: "sequential_23"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_51 (Dense)             (None, 128)               819328    
_________________________________________________________________
dense_52 (Dense)             (None, 32)                4128      
_________________________________________________________________
dense_53 (Dense)             (None, 4)                 132       
Total params: 823,588
Trainable params: 823,588
Non-trainable params: 0
_________________________________________________________________
Epoch 1/5
210/210 [==============================] - 0s 2ms/sample - loss: 1.3860 - acc: 0.2476
Epoch 2/5
210/210 [==============================] - 0s 256us/sample - loss: 1.3678 - acc: 0.3810
Epoch 3/5
210/210 [==============================] - 0s 263us/sample - loss: 1.3375 - acc: 0.3667
Epoch 4/5
210/210 [==============================] - 0s 265us/sample - loss: 1.2987 -

In [154]:
X_train_ms_Norm = X_train_ms_Norm_NN.reshape(210,128,50)
X_test_ms_Norm = X_test_ms_Norm_NN.reshape(59,128,50)

In [155]:
model_ms_CNN_Norm  = tf.keras.models.Sequential()

model_ms_CNN_Norm.add( tf.keras.layers.Conv1D(filters= 8, kernel_size= 3, padding = 'same', activation= 'relu', input_shape =[128,50]))
model_ms_CNN_Norm.add( tf.keras.layers.MaxPool1D(pool_size= 2, strides = 1, padding = 'same'))
model_ms_CNN_Norm.add(tf.keras.layers.Dropout(0.25))

model_ms_CNN_Norm.add(tf.keras.layers.Flatten())

model_ms_CNN_Norm.add(tf.keras.layers.Dense(units = 4, activation= 'softmax'))

model_ms_CNN_Norm.summary()

model_ms_CNN_Norm.compile(optimizer="adam", loss='categorical_crossentropy', metrics=['accuracy'])

model_ms_CNN_Norm.fit(X_train_ms_Norm, Y_train, epochs = 5)
_,acc = model_ms_CNN_Norm.evaluate(X_test_ms_Norm, Y_test)
print('\n CNN Accuracy is ',acc)

Model: "sequential_24"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_8 (Conv1D)            (None, 128, 8)            1208      
_________________________________________________________________
max_pooling1d_8 (MaxPooling1 (None, 128, 8)            0         
_________________________________________________________________
dropout_12 (Dropout)         (None, 128, 8)            0         
_________________________________________________________________
flatten_6 (Flatten)          (None, 1024)              0         
_________________________________________________________________
dense_54 (Dense)             (None, 4)                 4100      
Total params: 5,308
Trainable params: 5,308
Non-trainable params: 0
_________________________________________________________________
Epoch 1/5
210/210 [==============================] - 0s 2ms/sample - loss: 1.3833 - acc: 0.3048
Epoch 2/5
210/210 [==

In [156]:
model_ms_RNN_Norm = tf.keras.models.Sequential()
model_ms_RNN_Norm.add(tf.keras.layers.LSTM(150, input_shape= (128,50)))
model_ms_RNN_Norm.add(tf.keras.layers.Dropout(0.2))
model_ms_RNN_Norm.add(tf.keras.layers.Dense(units = 4, activation= 'softmax'))
model_ms_RNN_Norm.summary()

model_ms_RNN_Norm.compile(optimizer="adam", loss='categorical_crossentropy', metrics=['accuracy'])
model_ms_RNN_Norm.fit(X_train_ms_Norm, Y_train, epochs= 5)
_,acc = model_ms_RNN_Norm.evaluate(X_test_ms_Norm, Y_test)
print('\n RNN Accuracy is ',acc)



Model: "sequential_25"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_4 (LSTM)                (None, 150)               120600    
_________________________________________________________________
dropout_13 (Dropout)         (None, 150)               0         
_________________________________________________________________
dense_55 (Dense)             (None, 4)                 604       
Total params: 121,204
Trainable params: 121,204
Non-trainable params: 0
_________________________________________________________________
Epoch 1/5
210/210 [==============================] - 3s 13ms/sample - loss: 1.3818 - acc: 0.3286
Epoch 2/5
210/210 [==============================] - 3s 13ms/sample - loss: 1.3586 - acc: 0.3429
Epoch 3/5
210/210 [==============================] - 2s 8ms/sample - loss: 1.3832 - acc: 0.3429
Epoch 4/5
210/210 [==============================] - 2s 7ms/sample - loss: 1.3576 - acc

In [162]:
X_mean_ms_train = np.empty([210,128]) 
lc = X_train_ms.shape[0]
for i in range(lc):
    for j in range(128):
        X_mean_ms_train[i][j] = sum(X_train_ms[i][j])/len(X_train_ms[i][j])

In [164]:
X_mean_ms_test = np.empty([59,128]) 
lc = X_test_ms.shape[0]
for i in range(lc):
    for j in range(128):
        X_mean_ms_test[i][j] = sum(X_test_ms[i][j])/len(X_test_ms[i][j])

In [166]:
rf_ms = RandomForestClassifier(n_estimators= 1000, random_state= 42)
rf_ms.fit(X_mean_ms_train, y_notenc_train)
rf_ms_pred = rf_ms.predict(X_mean_ms_test)
print(accuracy_score(y_notenc_test, rf_ms_pred))

0.3220338983050847


In [169]:
svc_ms = SVC()
svc_ms.fit(X_mean_ms_train, y_notenc_train)
svc_ms_pred = svc_ms.predict(X_mean_ms_test)
print(accuracy_score(y_notenc_test, svc_ms_pred))

0.3389830508474576


/Users/rohithjanardhan/mlpath/yourenv/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [170]:
X_mean_ms_train_Norm = np.empty([210,128]) 
lc = X_train_ms_Norm.shape[0]
for i in range(lc):
    for j in range(128):
        X_mean_ms_train_Norm[i][j] = sum(X_train_ms_Norm[i][j])/len(X_train_ms_Norm[i][j])

In [171]:
X_mean_ms_test_Norm = np.empty([59,128]) 
lc = X_test_ms_Norm.shape[0]
for i in range(lc):
    for j in range(128):
        X_mean_ms_test_Norm[i][j] = sum(X_test_ms_Norm[i][j])/len(X_test_ms_Norm[i][j])

In [172]:
rf_norm_ms = RandomForestClassifier(n_estimators=1000, random_state=42)
rf_norm_ms.fit(X_mean_ms_train_Norm, y_notenc_train)
rf_pred_norm_ms = rf_norm_ms.predict(X_mean_ms_test_Norm)
print(accuracy_score(y_notenc_test, rf_pred_norm_ms))

0.2711864406779661


In [173]:
sv_norm_ms = SVC()
sv_norm_ms.fit(X_mean_ms_train_Norm, y_notenc_train)
sv_norm_ms_pred = sv_norm_ms.predict(X_mean_ms_test_Norm)
print(accuracy_score(y_notenc_test, sv_norm_ms_pred))

0.2711864406779661


/Users/rohithjanardhan/mlpath/yourenv/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
